language: objective-c

before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
    - cd "exampleProjects/IncrementalStore"
    # 32-bit tests
    - xctool -sdk iphonesimulator -scheme "Incremental Store Demo" clean test -destination "name=iPhone 5"
    - cat ../../vendor/sqlcipher/config.log
    # 64-bit tests
    - xctool -sdk iphonesimulator -scheme "Incremental Store Demo" clean test -destination "name=iPhone 5s"
    - cat ../../vendor/sqlcipher/config.log